# Generated by Django 2.2.5 on 2020-06-06 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=20)),
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
            ],
        ),
        migrations.CreateModel(
            name='Topping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('pizza', models.ManyToManyField(to='menu.Pizza')),
            ],
            options={
                'ordering': ['added_on'],
            },
        ),
        migrations.CreateModel(
            name='Sauce',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, null=True)),
                ('added_on', models.DateTimeField(auto_now_add=True)),
                ('pizza', models.ManyToManyField(to='menu.Pizza')),
            ],
            options={
                'ordering': ['added_on'],
            },
        ),
    ]
