# Generated by Django 2.2.5 on 2020-06-08 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='topping',
            name='pizza',
        ),
        migrations.AddField(
            model_name='pizza',
            name='sauce',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='pizza',
            name='topping',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.DeleteModel(
            name='Sauce',
        ),
        migrations.DeleteModel(
            name='Topping',
        ),
    ]
